### ISSUE TITLE
Play RTSP stream

### ISSUE THREAD

**Issue by dankop123** [gstreamer-java/gst1-java-examples#11]
Hi,
I'm trying to display a video from RTSP stream using gstreamer. I've modified `CameraTest.java` example to:
`Bin bin = Bin.launch("rtspsrc location=rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov ! decodebin ! autovideosink", true);`

When I launch `gst-launch-1.0 rtspsrc location=rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov latency=0 ! decodebin ! autovideosink` in terminal it's working ok, but when I launch a java example I got 2 windows like on the screen below.

![screen shot 2018-08-13 at 16 50 38](https://user-images.githubusercontent.com/35372166/44039306-1bded4c0-9f19-11e8-9bc7-183e10ba9ceb.png)

There is also an error in console
`(CameraTest:93274): GStreamer-CRITICAL **: guint64 _gst_util_uint64_scale_int(guint64, gint, gint, gint): assertion `denom > 0' failed`

I'm using gst1-java-core 0.9.3 and osx. Can you help me to make this work? Thanks.

**Comment by neilcsmith-net** [comment]
You don't use `Bin.launch` with `autovideosink`!  `Bin.launch(String binDescription, boolean ghostUnlinkedPads)` is not the same as the CLI - that's `Pipeline.launch(String pipelineDescription)`.  The former is equivalent to `gst_parse_bin_from_description` and the latter to `gst_parse_launch()`.  See upstream docs at https://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/gstreamer-GstParse.html

Please come and ask on the mailing list at https://groups.google.com/forum/#!forum/gstreamer-java with a clearer idea of what exactly you're trying to do here.  Do you want it in Swing?  Two windows, one native, one empty JFrame, is exactly what I'd expect to see there.

Best wishes, Neil
