### ISSUE TITLE
RTSP stream to MP4 with audio

### ISSUE THREAD

**Issue by Th0ru5** [gstreamer-java/gst1-java-examples#12]
Hello,
I'm using one of your examples. Exactly TestFootageCapture.java. I didn't change anything except aac codec because i can not install and use faac so i took voaacenc.

When i start recording i'm getting this message:
** (gst1-java-core:6290): CRITICAL **: 23:14:32.091: gst_app_src_push_internal: assertion 'GST_IS_BUFFER (buffer)' failed

I found solution for this. The solution is removing sample.dispose(); from newSample function but after removing the line my RAM is eaten like cookie by the JVM.

Is this a bug in your example or the aac codec is the issue?

**Comment by neilcsmith-net** [comment]
Possibly!  I only updated that example to compile with 1.x, not looked at it in depth.  You're probably better asking on the mailing list (see main project README).  It's possible that there's an issue with copy() or disown() in v1.  Removing sample.dispose() is definitely not the right answer - it will cause a massive memory leak.

Also try altering to use a basic test input stream to see if that replicates the issue without the codec change.

Pinging @tendwong to see if he can have a look at this again?

**Comment by Th0ru5** [comment]
I tried many input streams and always it appears.
I discover one more thing, after removing the AppSink for audio all starts working fine, but without audio of course.
I don't understand why the audio sample can't be disposed.

Maybe this informations will help you fix the issue.
Please let me know if you find something useful.

I have idea to work it around. I will try it after work and will let you know if it worked.

**Comment by Th0ru5** [comment]
Ok i checked my idea and it works perfectly.
My idea was to get bytes from Buffer object and put them into array, next I'm creating new Buffer object in function needData and writing the byte array to the Buffer object.

If someone will have the same issue and will not be able to solve it on his own, I can help.

To authors: If You fix the problem with copy() or disown() let us know.
Thanks.

**Comment by neilcsmith-net** [comment]
For info I've opened https://github.com/gstreamer-java/gst1-java-core/issues/171

A better idea for a workaround is to change the queue to use `Sample` (making sure not to dispose of the Sample if pushed to the queue!)

Then, in `AppSrc.NEED_DATA` do

```java
Sample sample = queue.take();
Buffer buffer = sample.getBuffer();
Natives.ref(buffer); // extra ref so that sample dispose doesn't break it.
elem.pushBuffer(buffer);
sample.dispose();                        
```

**Comment by tendwong** [comment]
Hi Neil,
Just saw this message and I’m a little busy at the moment. For your info, I am currently doing this for pushing buffers to the sink from AppSrc.

        Buffer dstBuffer = new Buffer(capacity);
        dstBuffer.map(true).asIntBuffer().put(drawPixels);
        dstBuffer.unmap();

        // Set other dstBuffer flags etc…

        dstBuffer.disown();

elem.pushBuffer(dstBuffer);

Not sure if this helps out whoever is asking the question.

Thanks and regards,
Tend.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by neilcsmith-net** [comment]
@tendwong Thanks for looking.  Not sure creating a new Buffer each time is a better option than keeping the Sample around though!  We might also look at extending the BufferPool mapping for use outside of AllocationQuery.
