### ISSUE TITLE
tee plugin code example request

### ISSUE THREAD

**Issue by chenjeff622** [gstreamer-java/gst1-java-examples#13]
how to display and record at same time. attachment is my sample code.
it will works success if i use only queue1 or queue2 .
it will works fail when i use tee plugin to connect queue1 and queue2.
does it have any tee plugin code sample for java ?
[test.txt](https://github.com/gstreamer-java/gst1-java-examples/files/3638393/test.txt)

**Comment by neilcsmith-net** [comment]
Please use the mailing list.  I'll keep this open as a request for such an example though.
