### ISSUE TITLE
WebRTCSendRecv

### ISSUE THREAD

**Issue by gatordevin** [gstreamer-java/gst1-java-examples#20]
Hello I have cloned your WebRTCSendRecv example and am encountering some weird issues. The program runs just fine for a second or two and I am able to see the ball test source in my web browser. However, after a couple of seconds the stream goes away and I encounter the following errors from the program.

`SEVERE: Error from source : BaseSrc: [nicesrc0], with code : 1, and message : Internal data stream error.
Jun 29, 2021 6:18:42 PM org.freedesktop.gstreamer.examples.WebRTCSendRecv lambda$setupPipeLogging$5
SEVERE: Error from source : Element: [queue2], with code : 1, and message : Internal data stream error.
Jun 29, 2021 6:18:42 PM org.freedesktop.gstreamer.examples.WebRTCSendRecv lambda$setupPipeLogging$7
INFO: Pipe state changed from PLAYING to PAUSED
Jun 29, 2021 6:18:42 PM org.freedesktop.gstreamer.examples.WebRTCSendRecv lambda$setupPipeLogging$7
INFO: Pipe state changed from PAUSED to READY`

Any ideas? I am using Java JDK 14 and the latest version of both GStreamer and java GStreamer. My end goal is to create a Java webrtc app using GStreamer that would allow me to remotely drive a robot on the same network.

**Comment by neilcsmith-net** [comment]
Do you hear anything?  This might be down to the test web page (used for the upstream examples) not getting permissions for audio correctly.  I have to use the browser's permissions page to explicitly allow audio for this to work.  That is mentioned in the readme.  Or try commenting out lines 59-60 - https://github.com/gstreamer-java/gst1-java-examples/blob/master/WebRTCSendRecv/src/main/java/org/freedesktop/gstreamer/examples/WebRTCSendRecv.java#L59

**Comment by gatordevin** [comment]
I do hear the sin wave audio but it's only for a few seconds same as the video. I have tried with the audio source and both exhibit the same behavior.

**Comment by neilcsmith-net** [comment]
OK, thinking about it, with those elements this might be the incoming stream back that's causing issues.  Do you get as far as `Received decoded stream with caps` in the output?  If so, what caps?  Try uncommenting the line in `main` that enables GStreamer's debug messages too.

I'm not sure what the issue you're seeing is exactly.  I took the previously half working (send only) [Java example][1] from upstream, and ported the receiving setup from [C / Python][2] examples to it, as well as a few other updates.  Possible I missed something.  It works where I've tested it so far, but not tried many combinations.  And it's possible it's a problem on the other end (test server) with some combinations.

You might want to try our [mailing list][3] or the [upstream mailing list][4] - likely to get more input there.

[1]: https://gitlab.freedesktop.org/gstreamer/gst-examples/-/blob/master/webrtc/sendrecv/gst-java/src/main/java/WebrtcSendRecv.java
[2]: https://gitlab.freedesktop.org/gstreamer/gst-examples/-/tree/master/webrtc/sendrecv/gst
[3]: https://groups.google.com/forum/#!forum/gstreamer-java
[4]: https://lists.freedesktop.org/mailman/listinfo/gstreamer-devel

**Comment by gatordevin** [comment]
Just had a little run-in with COVID so haven't been able to look at the problem more. I tested the program on my laptop rather than desktop which has theoretically the same setup. Java 14 Windows 10 and it worked perfectly. Not sure what other differences could cause issues. I will try your recommended fix on my desktop.

**Comment by neilcsmith-net** [comment]
Closing this.  If any more questions about the examples, please use https://github.com/gstreamer-java/gst1-java-core/discussions
