### ISSUE TITLE
JavaFX support

### ISSUE THREAD

**Issue by Abu-Abdullah** [gstreamer-java/gst1-java-examples#4]
Hi,

im trying to use the gst1-java with JavaFX. i'm trying to recode SimpleVideoComponent to be native JavaFX code without any swing component to utalise the javaFX hardware acceleration stack. the component that can replace JComponent is javafx.scene.canvas.Canvas but i couldn't manage it.

there is a way to embed swing in JavaFX using SwingNode but this is not the optimum solution as it will not be handled by JavaFX rendering stack (hardware acceleration might not be working in this case). in addition clean code is recommended in all cases.

any support is appreciated. is there a plan to import the code to JavaFX

**Comment by neilcsmith-net** [comment]
Please see pull request #3 for an example of this - you should be able to download it directly from https://github.com/lukasEeeE/gst1-java-examples

As explained in that pull request, I won't be adding JavaFX dependencies to this repository, at least until JavaFX becomes part of the JDK.  I'm hoping others will take on JavaFX example and utilities in a separate repository here - I don't use JavaFX for anything so I'm not the right person to work on it! :smile:

Best wishes, Neil

**Comment by Abu-Abdullah** [comment]
thanks.
