### ISSUE TITLE
Include more sophisticated examples

### ISSUE THREAD

**Issue by dyorgio** [gstreamer-java/gst1-java-examples#6]
Hi, very nice lib man!

I would like to see more complex/sophisticate examples on this repository.

Some ideias:

1) Read file video and send to youtube (RTP)
2) Capture video frames as Java AWT Images
3) modify frames using Java AWT APIs.
4) Mix two sources (file, webcam overlay) into one file.

I want to make a lib that can be used to add dynamic content to videos and stream it, like Prixe, but as a lib.

**Comment by neilcsmith-net** [comment]
Thanks!  Pull requests welcome :wink:

The old GStreamer 0.10 bindings have many more examples in the repository - at some point these need porting over, and some news ones added, but you might find something useful that you can adapt in there - https://github.com/gstreamer-java/gstreamer-java/tree/master/gstreamer-java/src/org/gstreamer/example
