### ISSUE TITLE
troubleshoot window that stays black after choosing media

### ISSUE THREAD

**Issue by mutantbob** [gstreamer-java/gst1-java-examples#7]
When I run the MultiSinkExample inside IntelliJ IDEA and choose one of the MP4 files I have on my hard drive the window stays black.

There is absolutely no output that helps me figure out what is going wrong.  I don't know if it is a failure of gstreamer, a failure of the java bindings, or some weird environmental issue.

Linux herakleion 4.12.12-bob #38 SMP Sat Dec 9 23:32:34 EST 2017 x86_64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz GenuineIntel GNU/Linux

**Comment by neilcsmith-net** [comment]
The most obvious suggestion is that GStreamer is missing plugins for mp4 on your system, but there are multiple possible reasons.  What about other files with different codecs?  That example was written for a client with a particular need - it's possible it's got an issue.

In terms of testing the library and bindings are working together OK, the camera example is a better bet.  It should default to the video test source if you have no camera.

I realise there's a need for more examples here - I'll try and find some time to tidy up other code I have soon.  The bindings are currently used in multiple open-source and commercial projects, so should be fairly stable.

**Comment by mutantbob** [comment]
you are correct.  I was missing some plugins.  It took me a long time experimenting with `gst-launch playbin uri=$uri` but eventually I was able to get things working.  Is there any way the examples could be upgraded to display the error messages that are coming from the gstreamer framework so the next person with my problem at least knows to try `gst-launch` ?

**Comment by neilcsmith-net** [comment]
Errors will already pass through to standard out.  Try setting the `GST_DEBUG` environment variable - see https://gstreamer.freedesktop.org/documentation/tutorials/basic/debugging-tools.html  I'm using NetBeans rather than IntelliJ, but I'm fairly sure there's a UI there too for doing this in Maven projects.

I'll look at some way of reporting pipeline problems in the examples, but don't want to complicate them too much.
